import React from 'react'
import { Container } from "@material-ui/core"

const Reflections = () => (
  <>
    {" "}
    
    <Container>
      {" "}

      <h1>Reflections</h1>
      <h2>2020/2021 HSA Researching Interactions with Technology</h2>
      <p>In the context of the Human Sciences A (HSA) Module, I conducted a research study project relevant to music collections. In this section, I want to reflect on the progress I have made over the past months along with the observations I cumulated along the way.</p>
      <h2>What did I learn?</h2>
      <p>My expectations for the course were to understand better how to carry on and evaluate research. I wanted to develop the skills needed for user research that lead the development and design of great products. While the end goal of this particular research study was not to build anything, I was able to see how important it is to gain insights on how people interact with technology in certain areas. The analysis of the data gathered can highlight what a customer needs rather than what he/she wants and thus, be relevant to the target audience. The intended outcome of my study was to identify if the music streaming services offered the tools and features to enable collectors to relate to online music as they did with physical music records. The results would help identify any gaps or areas needing improvement in turn. I am glad to say I have gain knowledge towards that purpose in completing my research study.</p>
      <p>The biggest challenge was actually to formulate the research question properly and narrow down my research topic. Initially, I wanted to look at digital collections as a whole. I have come to realise that there are questions behind everything and the only way to find answers is to focus on a specific question, limiting the scope of inquiry as much as possible. I spent hours perusing the literature available on online resources such as the DCU library and researchgate.net. Some readings were helpful, others dense and confusing, but overall it was eye-opening to explore the wealth of knowledge available online.</p>
      <p>I chose to focus on a comparison between music collections (physical and via streaming services) as there was a gap in the literature available, especially in the context of a specific generation. Based on previous conversations with friends and peers, I anticipated that a majority of the Millennials would naturally shift to the latest music technology since they had gone through multiple changes already, from cassettes to Ipods. However, I did not know where the physical music collections stood in their opinion. The relationship element is where the research project really began to take form for me.</p>
      <h2>What went well?</h2>
      <p>Because of the COVID19 pandemic, I was unable to conduct face-to-face interviews. However, this turned out to be quite helpful. Since everyone worked and interacted online, the interviewees I contacted were already familiar with the online tools available for video conferencing. Using video conferencing was great as well, since it permitted a bit more flexibility in terms of scheduling and recording the interview process. </p>
      <p>I also discovered that I enjoyed the data gathering process the most out of all the facets of the research study. Perhaps it is due to the current isolation climate, but I thoroughly liked interviewing music enthusiasts and conversing with them, even if it was partially structured.&nbsp; I found the interview process initially tricky, especially in terms of avoiding leading questions and finding a good pace in delivering questions. However, I improved as I went along and learned to ask better questions as well. The participants were amazing and passionate, they gave wonderful insights, and it made the whole experience a gratifying one. Transcribing the interviews was greatly sped up by Otter.ai; however, it did not replace my revision while relistening to the conversations. I really enjoyed refining the themes within a recording and discovering patterns or angles I didn&rsquo;t expect. </p>
      <h2>What could I have done better?</h2>
      <p>I personally had limited experience in terms of conducting research and I had little confidence in writing academic papers; the dissertation was especially daunting. At first, putting all the literature together for the literature review was intimidating due to the quantity of papers reviewed, but I enjoyed refining the concepts identified and what I intended to explore. It was a necessary step towards organising my thoughts more clearly. Later on, the structure of the dissertation was mystifying to me and I am glad that I could reach out to the writing centre within the university to receive advice.&nbsp; Additionally, I was able to keep in touch with my supervisor regularly to confirm my train of thought and the approaches chosen during the data gathering process, for instance. My takeaway is that I have to write to become a better writer and since that was something I was not used to, it took me longer to produce something I was satisfied with.</p>
      <p>Another challenge I experienced was that recruiting participants for the anonymous survey took more time than anticipated. I would not normally use social media other than for a quick overview of the news, so I did not know how to best reach the greatest number of people in a short time. At first, I shared the information with friends, family and peers, but the reach of this initial group of people could only go so far. I could not recruit my coworkers for the survey to follow the company&rsquo;s policy and did not know where to gain visibility.&nbsp; Thanks to the input of other students, I decided to create a Facebook profile and join Facebook Groups, where I&nbsp; invited music enthusiasts to share their opinions. This helped me collect close to 100 survey responses, used later to narrow down a sample of participants for the interviews.</p>
      <p>An element I would revisit given more time and resources is the type of sampling used in the research study. While extremely convenient (as the name gives it away), convenience sampling is not widely regarded as credible as it can lead to biased results. For instance, the convenience sample of Millennial music enthusiasts were drawn from survey participants coming from social media sources and online communities (Facebook Groups) built around music collections. These participants may not be representative of all Millennials community members. While I was aware of the limitations of this sampling technique, I did not find an alternative that would suit the resources of the research study at the time.</p>
      <h2>Long-term implications</h2>
      <p>I now understand that conducting research is akin to running a marathon, where it is essential to build solid foundations and keep a steady pace. I also discovered how important it is to keep references and supporting documentation at hand. During the entire length of the project, I tried to note down every element that might become useful at a later time. I found that keeping track of content and my progress via handwritten notes was my preferred method; still, I made sure to copy them and add them into a digital document. I think notetaking is a transferable skill and will be of great use for any other subject I decide to delve into.</p>
      <p>Back to the marathon allegory, I also realised that this research project would take time, and that it was perfectly fine, that I should not rush. I had be patient, celebrate every milestone however small and complete the necessary processes before moving on to writing about the findings. I was surprised by the time I took to complete the data analysis, for one thing. I revisited the themes many times. It makes sense -- in any industry, there is no improvisation or shortcuts permitted in the design and creation of purposeful products. While there might be an end goal, in order for it to be valid and representative, there needs to be a structure and reasoning in place. Making time to go through the correct process is an important takeaway for me, especially when nowadays I almost expect immediate answers and instantaneous solutions to technical problems.</p>
      <h2>Conclusion</h2>
      <p>The research process has proven to be more specific and more complex than I would have anticipated. In the previous academic year, while I studied the different interaction design research concepts, I did not realise the effort and structure involved to produce verifiable and reliable results. I would recommend this experience as, while it was challenging at times, it feels rewarding as I go back over all the work accomplished over a few months. Moreover, I am now curious and eager to explore the additional questions raised during the research study, so it is likely that the project I undertook opened the door to additional investigation on my part.</p>
    </Container>
  </>
)

export default Reflections
